// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: special-admin.proto

package special_admin_v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LittlePictureInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Picture       []byte                 `protobuf:"bytes,1,opt,name=picture,proto3" json:"picture,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LittlePictureInfo) Reset() {
	*x = LittlePictureInfo{}
	mi := &file_special_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LittlePictureInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LittlePictureInfo) ProtoMessage() {}

func (x *LittlePictureInfo) ProtoReflect() protoreflect.Message {
	mi := &file_special_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LittlePictureInfo.ProtoReflect.Descriptor instead.
func (*LittlePictureInfo) Descriptor() ([]byte, []int) {
	return file_special_admin_proto_rawDescGZIP(), []int{0}
}

func (x *LittlePictureInfo) GetPicture() []byte {
	if x != nil {
		return x.Picture
	}
	return nil
}

func (x *LittlePictureInfo) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

type PictureInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Picture       []byte                 `protobuf:"bytes,2,opt,name=picture,proto3" json:"picture,omitempty"`
	MimeType      string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PictureInfo) Reset() {
	*x = PictureInfo{}
	mi := &file_special_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PictureInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PictureInfo) ProtoMessage() {}

func (x *PictureInfo) ProtoReflect() protoreflect.Message {
	mi := &file_special_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PictureInfo.ProtoReflect.Descriptor instead.
func (*PictureInfo) Descriptor() ([]byte, []int) {
	return file_special_admin_proto_rawDescGZIP(), []int{1}
}

func (x *PictureInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PictureInfo) GetPicture() []byte {
	if x != nil {
		return x.Picture
	}
	return nil
}

func (x *PictureInfo) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

type CreatePictureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentId      string                 `protobuf:"bytes,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Picture       *LittlePictureInfo     `protobuf:"bytes,2,opt,name=picture,proto3" json:"picture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePictureRequest) Reset() {
	*x = CreatePictureRequest{}
	mi := &file_special_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePictureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePictureRequest) ProtoMessage() {}

func (x *CreatePictureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_special_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePictureRequest.ProtoReflect.Descriptor instead.
func (*CreatePictureRequest) Descriptor() ([]byte, []int) {
	return file_special_admin_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePictureRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *CreatePictureRequest) GetPicture() *LittlePictureInfo {
	if x != nil {
		return x.Picture
	}
	return nil
}

type DeletePictureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePictureRequest) Reset() {
	*x = DeletePictureRequest{}
	mi := &file_special_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePictureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePictureRequest) ProtoMessage() {}

func (x *DeletePictureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_special_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePictureRequest.ProtoReflect.Descriptor instead.
func (*DeletePictureRequest) Descriptor() ([]byte, []int) {
	return file_special_admin_proto_rawDescGZIP(), []int{3}
}

func (x *DeletePictureRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersRequest) Reset() {
	*x = GetUsersRequest{}
	mi := &file_special_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersRequest) ProtoMessage() {}

func (x *GetUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_special_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersRequest.ProtoReflect.Descriptor instead.
func (*GetUsersRequest) Descriptor() ([]byte, []int) {
	return file_special_admin_proto_rawDescGZIP(), []int{4}
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Surname       string                 `protobuf:"bytes,2,opt,name=surname,proto3" json:"surname,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_special_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_special_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_special_admin_proto_rawDescGZIP(), []int{5}
}

func (x *UserInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserInfo) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

func (x *UserInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserInfo) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type GetUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserInfo            `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersResponse) Reset() {
	*x = GetUsersResponse{}
	mi := &file_special_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersResponse) ProtoMessage() {}

func (x *GetUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_special_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersResponse.ProtoReflect.Descriptor instead.
func (*GetUsersResponse) Descriptor() ([]byte, []int) {
	return file_special_admin_proto_rawDescGZIP(), []int{6}
}

func (x *GetUsersResponse) GetUsers() []*UserInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

type GetIventInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIventInfoRequest) Reset() {
	*x = GetIventInfoRequest{}
	mi := &file_special_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIventInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIventInfoRequest) ProtoMessage() {}

func (x *GetIventInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_special_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIventInfoRequest.ProtoReflect.Descriptor instead.
func (*GetIventInfoRequest) Descriptor() ([]byte, []int) {
	return file_special_admin_proto_rawDescGZIP(), []int{7}
}

func (x *GetIventInfoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetIventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIventsRequest) Reset() {
	*x = GetIventsRequest{}
	mi := &file_special_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIventsRequest) ProtoMessage() {}

func (x *GetIventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_special_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIventsRequest.ProtoReflect.Descriptor instead.
func (*GetIventsRequest) Descriptor() ([]byte, []int) {
	return file_special_admin_proto_rawDescGZIP(), []int{8}
}

type CreateIventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Datetime      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=datetime,proto3" json:"datetime,omitempty"`
	Price         *wrapperspb.Int64Value `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	TotalSeats    int64                  `protobuf:"varint,5,opt,name=total_seats,json=totalSeats,proto3" json:"total_seats,omitempty"`
	OccupiedSeats *wrapperspb.Int64Value `protobuf:"bytes,6,opt,name=occupied_seats,json=occupiedSeats,proto3" json:"occupied_seats,omitempty"`
	LittlePicture *LittlePictureInfo     `protobuf:"bytes,7,opt,name=little_picture,json=littlePicture,proto3" json:"little_picture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIventRequest) Reset() {
	*x = CreateIventRequest{}
	mi := &file_special_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIventRequest) ProtoMessage() {}

func (x *CreateIventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_special_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIventRequest.ProtoReflect.Descriptor instead.
func (*CreateIventRequest) Descriptor() ([]byte, []int) {
	return file_special_admin_proto_rawDescGZIP(), []int{9}
}

func (x *CreateIventRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateIventRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateIventRequest) GetDatetime() *timestamppb.Timestamp {
	if x != nil {
		return x.Datetime
	}
	return nil
}

func (x *CreateIventRequest) GetPrice() *wrapperspb.Int64Value {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *CreateIventRequest) GetTotalSeats() int64 {
	if x != nil {
		return x.TotalSeats
	}
	return 0
}

func (x *CreateIventRequest) GetOccupiedSeats() *wrapperspb.Int64Value {
	if x != nil {
		return x.OccupiedSeats
	}
	return nil
}

func (x *CreateIventRequest) GetLittlePicture() *LittlePictureInfo {
	if x != nil {
		return x.LittlePicture
	}
	return nil
}

type UpdateIventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Datetime      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=datetime,proto3,oneof" json:"datetime,omitempty"`
	Price         *wrapperspb.Int64Value `protobuf:"bytes,5,opt,name=price,proto3" json:"price,omitempty"`
	TotalSeats    *int64                 `protobuf:"varint,6,opt,name=total_seats,json=totalSeats,proto3,oneof" json:"total_seats,omitempty"`
	OccupiedSeats *wrapperspb.Int64Value `protobuf:"bytes,7,opt,name=occupied_seats,json=occupiedSeats,proto3" json:"occupied_seats,omitempty"`
	LittlePicture *LittlePictureInfo     `protobuf:"bytes,8,opt,name=little_picture,json=littlePicture,proto3,oneof" json:"little_picture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateIventRequest) Reset() {
	*x = UpdateIventRequest{}
	mi := &file_special_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIventRequest) ProtoMessage() {}

func (x *UpdateIventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_special_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIventRequest.ProtoReflect.Descriptor instead.
func (*UpdateIventRequest) Descriptor() ([]byte, []int) {
	return file_special_admin_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateIventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateIventRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateIventRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateIventRequest) GetDatetime() *timestamppb.Timestamp {
	if x != nil {
		return x.Datetime
	}
	return nil
}

func (x *UpdateIventRequest) GetPrice() *wrapperspb.Int64Value {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *UpdateIventRequest) GetTotalSeats() int64 {
	if x != nil && x.TotalSeats != nil {
		return *x.TotalSeats
	}
	return 0
}

func (x *UpdateIventRequest) GetOccupiedSeats() *wrapperspb.Int64Value {
	if x != nil {
		return x.OccupiedSeats
	}
	return nil
}

func (x *UpdateIventRequest) GetLittlePicture() *LittlePictureInfo {
	if x != nil {
		return x.LittlePicture
	}
	return nil
}

type DeleteIventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteIventRequest) Reset() {
	*x = DeleteIventRequest{}
	mi := &file_special_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteIventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIventRequest) ProtoMessage() {}

func (x *DeleteIventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_special_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIventRequest.ProtoReflect.Descriptor instead.
func (*DeleteIventRequest) Descriptor() ([]byte, []int) {
	return file_special_admin_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteIventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UserIventInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserNickname   string                 `protobuf:"bytes,2,opt,name=user_nickname,json=userNickname,proto3" json:"user_nickname,omitempty"`
	NumberOfGuests int64                  `protobuf:"varint,3,opt,name=number_of_guests,json=numberOfGuests,proto3" json:"number_of_guests,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserIventInfo) Reset() {
	*x = UserIventInfo{}
	mi := &file_special_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIventInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIventInfo) ProtoMessage() {}

func (x *UserIventInfo) ProtoReflect() protoreflect.Message {
	mi := &file_special_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIventInfo.ProtoReflect.Descriptor instead.
func (*UserIventInfo) Descriptor() ([]byte, []int) {
	return file_special_admin_proto_rawDescGZIP(), []int{12}
}

func (x *UserIventInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserIventInfo) GetUserNickname() string {
	if x != nil {
		return x.UserNickname
	}
	return ""
}

func (x *UserIventInfo) GetNumberOfGuests() int64 {
	if x != nil {
		return x.NumberOfGuests
	}
	return 0
}

type GetIventInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Datetime      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=datetime,proto3" json:"datetime,omitempty"`
	Price         int64                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	TotalSeats    int64                  `protobuf:"varint,6,opt,name=total_seats,json=totalSeats,proto3" json:"total_seats,omitempty"`
	OccupiedSeats int64                  `protobuf:"varint,7,opt,name=occupied_seats,json=occupiedSeats,proto3" json:"occupied_seats,omitempty"`
	LittlePicture *LittlePictureInfo     `protobuf:"bytes,8,opt,name=little_picture,json=littlePicture,proto3" json:"little_picture,omitempty"`
	Pictures      []*PictureInfo         `protobuf:"bytes,9,rep,name=pictures,proto3" json:"pictures,omitempty"`
	UserIvents    []*UserIventInfo       `protobuf:"bytes,10,rep,name=userIvents,proto3" json:"userIvents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIventInfoResponse) Reset() {
	*x = GetIventInfoResponse{}
	mi := &file_special_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIventInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIventInfoResponse) ProtoMessage() {}

func (x *GetIventInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_special_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIventInfoResponse.ProtoReflect.Descriptor instead.
func (*GetIventInfoResponse) Descriptor() ([]byte, []int) {
	return file_special_admin_proto_rawDescGZIP(), []int{13}
}

func (x *GetIventInfoResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetIventInfoResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetIventInfoResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetIventInfoResponse) GetDatetime() *timestamppb.Timestamp {
	if x != nil {
		return x.Datetime
	}
	return nil
}

func (x *GetIventInfoResponse) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GetIventInfoResponse) GetTotalSeats() int64 {
	if x != nil {
		return x.TotalSeats
	}
	return 0
}

func (x *GetIventInfoResponse) GetOccupiedSeats() int64 {
	if x != nil {
		return x.OccupiedSeats
	}
	return 0
}

func (x *GetIventInfoResponse) GetLittlePicture() *LittlePictureInfo {
	if x != nil {
		return x.LittlePicture
	}
	return nil
}

func (x *GetIventInfoResponse) GetPictures() []*PictureInfo {
	if x != nil {
		return x.Pictures
	}
	return nil
}

func (x *GetIventInfoResponse) GetUserIvents() []*UserIventInfo {
	if x != nil {
		return x.UserIvents
	}
	return nil
}

type IventInfoForList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Datetime      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=datetime,proto3" json:"datetime,omitempty"`
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	TotalSeats    int64                  `protobuf:"varint,5,opt,name=total_seats,json=totalSeats,proto3" json:"total_seats,omitempty"`
	OccupiedSeats int64                  `protobuf:"varint,6,opt,name=occupied_seats,json=occupiedSeats,proto3" json:"occupied_seats,omitempty"`
	LittlePicture *LittlePictureInfo     `protobuf:"bytes,7,opt,name=little_picture,json=littlePicture,proto3" json:"little_picture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IventInfoForList) Reset() {
	*x = IventInfoForList{}
	mi := &file_special_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IventInfoForList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IventInfoForList) ProtoMessage() {}

func (x *IventInfoForList) ProtoReflect() protoreflect.Message {
	mi := &file_special_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IventInfoForList.ProtoReflect.Descriptor instead.
func (*IventInfoForList) Descriptor() ([]byte, []int) {
	return file_special_admin_proto_rawDescGZIP(), []int{14}
}

func (x *IventInfoForList) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IventInfoForList) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *IventInfoForList) GetDatetime() *timestamppb.Timestamp {
	if x != nil {
		return x.Datetime
	}
	return nil
}

func (x *IventInfoForList) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *IventInfoForList) GetTotalSeats() int64 {
	if x != nil {
		return x.TotalSeats
	}
	return 0
}

func (x *IventInfoForList) GetOccupiedSeats() int64 {
	if x != nil {
		return x.OccupiedSeats
	}
	return 0
}

func (x *IventInfoForList) GetLittlePicture() *LittlePictureInfo {
	if x != nil {
		return x.LittlePicture
	}
	return nil
}

type GetIventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ivents        []*IventInfoForList    `protobuf:"bytes,1,rep,name=ivents,proto3" json:"ivents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIventsResponse) Reset() {
	*x = GetIventsResponse{}
	mi := &file_special_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIventsResponse) ProtoMessage() {}

func (x *GetIventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_special_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIventsResponse.ProtoReflect.Descriptor instead.
func (*GetIventsResponse) Descriptor() ([]byte, []int) {
	return file_special_admin_proto_rawDescGZIP(), []int{15}
}

func (x *GetIventsResponse) GetIvents() []*IventInfoForList {
	if x != nil {
		return x.Ivents
	}
	return nil
}

type GetItemInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemInfoRequest) Reset() {
	*x = GetItemInfoRequest{}
	mi := &file_special_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemInfoRequest) ProtoMessage() {}

func (x *GetItemInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_special_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemInfoRequest.ProtoReflect.Descriptor instead.
func (*GetItemInfoRequest) Descriptor() ([]byte, []int) {
	return file_special_admin_proto_rawDescGZIP(), []int{16}
}

func (x *GetItemInfoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemsRequest) Reset() {
	*x = GetItemsRequest{}
	mi := &file_special_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsRequest) ProtoMessage() {}

func (x *GetItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_special_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsRequest.ProtoReflect.Descriptor instead.
func (*GetItemsRequest) Descriptor() ([]byte, []int) {
	return file_special_admin_proto_rawDescGZIP(), []int{17}
}

type CreateItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	LittlePicture *LittlePictureInfo     `protobuf:"bytes,4,opt,name=little_picture,json=littlePicture,proto3" json:"little_picture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateItemRequest) Reset() {
	*x = CreateItemRequest{}
	mi := &file_special_admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemRequest) ProtoMessage() {}

func (x *CreateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_special_admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemRequest.ProtoReflect.Descriptor instead.
func (*CreateItemRequest) Descriptor() ([]byte, []int) {
	return file_special_admin_proto_rawDescGZIP(), []int{18}
}

func (x *CreateItemRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateItemRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateItemRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateItemRequest) GetLittlePicture() *LittlePictureInfo {
	if x != nil {
		return x.LittlePicture
	}
	return nil
}

type UpdateItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	LittlePicture *LittlePictureInfo     `protobuf:"bytes,5,opt,name=little_picture,json=littlePicture,proto3,oneof" json:"little_picture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItemRequest) Reset() {
	*x = UpdateItemRequest{}
	mi := &file_special_admin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemRequest) ProtoMessage() {}

func (x *UpdateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_special_admin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateItemRequest) Descriptor() ([]byte, []int) {
	return file_special_admin_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateItemRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateItemRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateItemRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateItemRequest) GetLittlePicture() *LittlePictureInfo {
	if x != nil {
		return x.LittlePicture
	}
	return nil
}

type DeleteItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteItemRequest) Reset() {
	*x = DeleteItemRequest{}
	mi := &file_special_admin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemRequest) ProtoMessage() {}

func (x *DeleteItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_special_admin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteItemRequest) Descriptor() ([]byte, []int) {
	return file_special_admin_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetItemInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	LittlePicture *LittlePictureInfo     `protobuf:"bytes,5,opt,name=little_picture,json=littlePicture,proto3" json:"little_picture,omitempty"`
	Pictures      []*PictureInfo         `protobuf:"bytes,6,rep,name=pictures,proto3" json:"pictures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemInfoResponse) Reset() {
	*x = GetItemInfoResponse{}
	mi := &file_special_admin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemInfoResponse) ProtoMessage() {}

func (x *GetItemInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_special_admin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemInfoResponse.ProtoReflect.Descriptor instead.
func (*GetItemInfoResponse) Descriptor() ([]byte, []int) {
	return file_special_admin_proto_rawDescGZIP(), []int{21}
}

func (x *GetItemInfoResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetItemInfoResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetItemInfoResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetItemInfoResponse) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GetItemInfoResponse) GetLittlePicture() *LittlePictureInfo {
	if x != nil {
		return x.LittlePicture
	}
	return nil
}

func (x *GetItemInfoResponse) GetPictures() []*PictureInfo {
	if x != nil {
		return x.Pictures
	}
	return nil
}

type ItemInfoForList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	LittlePicture *LittlePictureInfo     `protobuf:"bytes,4,opt,name=little_picture,json=littlePicture,proto3" json:"little_picture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemInfoForList) Reset() {
	*x = ItemInfoForList{}
	mi := &file_special_admin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemInfoForList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemInfoForList) ProtoMessage() {}

func (x *ItemInfoForList) ProtoReflect() protoreflect.Message {
	mi := &file_special_admin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemInfoForList.ProtoReflect.Descriptor instead.
func (*ItemInfoForList) Descriptor() ([]byte, []int) {
	return file_special_admin_proto_rawDescGZIP(), []int{22}
}

func (x *ItemInfoForList) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ItemInfoForList) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ItemInfoForList) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ItemInfoForList) GetLittlePicture() *LittlePictureInfo {
	if x != nil {
		return x.LittlePicture
	}
	return nil
}

type GetItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ItemInfoForList     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemsResponse) Reset() {
	*x = GetItemsResponse{}
	mi := &file_special_admin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsResponse) ProtoMessage() {}

func (x *GetItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_special_admin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsResponse.ProtoReflect.Descriptor instead.
func (*GetItemsResponse) Descriptor() ([]byte, []int) {
	return file_special_admin_proto_rawDescGZIP(), []int{23}
}

func (x *GetItemsResponse) GetItems() []*ItemInfoForList {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetOrderInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderInfoRequest) Reset() {
	*x = GetOrderInfoRequest{}
	mi := &file_special_admin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderInfoRequest) ProtoMessage() {}

func (x *GetOrderInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_special_admin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderInfoRequest.ProtoReflect.Descriptor instead.
func (*GetOrderInfoRequest) Descriptor() ([]byte, []int) {
	return file_special_admin_proto_rawDescGZIP(), []int{24}
}

func (x *GetOrderInfoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersRequest) Reset() {
	*x = GetOrdersRequest{}
	mi := &file_special_admin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersRequest) ProtoMessage() {}

func (x *GetOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_special_admin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersRequest.ProtoReflect.Descriptor instead.
func (*GetOrdersRequest) Descriptor() ([]byte, []int) {
	return file_special_admin_proto_rawDescGZIP(), []int{25}
}

type UpdateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        *string                `protobuf:"bytes,2,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Comment       *string                `protobuf:"bytes,3,opt,name=comment,proto3,oneof" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderRequest) Reset() {
	*x = UpdateOrderRequest{}
	mi := &file_special_admin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderRequest) ProtoMessage() {}

func (x *UpdateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_special_admin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderRequest) Descriptor() ([]byte, []int) {
	return file_special_admin_proto_rawDescGZIP(), []int{26}
}

func (x *UpdateOrderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateOrderRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *UpdateOrderRequest) GetComment() string {
	if x != nil && x.Comment != nil {
		return *x.Comment
	}
	return ""
}

type DeleteOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrderRequest) Reset() {
	*x = DeleteOrderRequest{}
	mi := &file_special_admin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrderRequest) ProtoMessage() {}

func (x *DeleteOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_special_admin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrderRequest.ProtoReflect.Descriptor instead.
func (*DeleteOrderRequest) Descriptor() ([]byte, []int) {
	return file_special_admin_proto_rawDescGZIP(), []int{27}
}

func (x *DeleteOrderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type OrderItemInfoForList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ItemId        string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int64                  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	LittlePicture *LittlePictureInfo     `protobuf:"bytes,6,opt,name=little_picture,json=littlePicture,proto3" json:"little_picture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItemInfoForList) Reset() {
	*x = OrderItemInfoForList{}
	mi := &file_special_admin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItemInfoForList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemInfoForList) ProtoMessage() {}

func (x *OrderItemInfoForList) ProtoReflect() protoreflect.Message {
	mi := &file_special_admin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemInfoForList.ProtoReflect.Descriptor instead.
func (*OrderItemInfoForList) Descriptor() ([]byte, []int) {
	return file_special_admin_proto_rawDescGZIP(), []int{28}
}

func (x *OrderItemInfoForList) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderItemInfoForList) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *OrderItemInfoForList) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *OrderItemInfoForList) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderItemInfoForList) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItemInfoForList) GetLittlePicture() *LittlePictureInfo {
	if x != nil {
		return x.LittlePicture
	}
	return nil
}

type GetOrderInfoResponse struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	Id             string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Number         string                  `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	UserNickname   string                  `protobuf:"bytes,3,opt,name=user_nickname,json=userNickname,proto3" json:"user_nickname,omitempty"`
	FormDate       *timestamppb.Timestamp  `protobuf:"bytes,4,opt,name=form_date,json=formDate,proto3" json:"form_date,omitempty"`
	CompletionDate *timestamppb.Timestamp  `protobuf:"bytes,5,opt,name=completion_date,json=completionDate,proto3" json:"completion_date,omitempty"`
	Comment        string                  `protobuf:"bytes,6,opt,name=comment,proto3" json:"comment,omitempty"`
	Status         string                  `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	OrderAmount    int64                   `protobuf:"varint,8,opt,name=order_amount,json=orderAmount,proto3" json:"order_amount,omitempty"`
	Items          []*OrderItemInfoForList `protobuf:"bytes,9,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetOrderInfoResponse) Reset() {
	*x = GetOrderInfoResponse{}
	mi := &file_special_admin_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderInfoResponse) ProtoMessage() {}

func (x *GetOrderInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_special_admin_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderInfoResponse.ProtoReflect.Descriptor instead.
func (*GetOrderInfoResponse) Descriptor() ([]byte, []int) {
	return file_special_admin_proto_rawDescGZIP(), []int{29}
}

func (x *GetOrderInfoResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetOrderInfoResponse) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *GetOrderInfoResponse) GetUserNickname() string {
	if x != nil {
		return x.UserNickname
	}
	return ""
}

func (x *GetOrderInfoResponse) GetFormDate() *timestamppb.Timestamp {
	if x != nil {
		return x.FormDate
	}
	return nil
}

func (x *GetOrderInfoResponse) GetCompletionDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletionDate
	}
	return nil
}

func (x *GetOrderInfoResponse) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *GetOrderInfoResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetOrderInfoResponse) GetOrderAmount() int64 {
	if x != nil {
		return x.OrderAmount
	}
	return 0
}

func (x *GetOrderInfoResponse) GetItems() []*OrderItemInfoForList {
	if x != nil {
		return x.Items
	}
	return nil
}

type OrderInfoForList struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Number         string                 `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	CompletionDate *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=completion_date,json=completionDate,proto3" json:"completion_date,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	OrderAmount    int64                  `protobuf:"varint,5,opt,name=order_amount,json=orderAmount,proto3" json:"order_amount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OrderInfoForList) Reset() {
	*x = OrderInfoForList{}
	mi := &file_special_admin_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfoForList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfoForList) ProtoMessage() {}

func (x *OrderInfoForList) ProtoReflect() protoreflect.Message {
	mi := &file_special_admin_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfoForList.ProtoReflect.Descriptor instead.
func (*OrderInfoForList) Descriptor() ([]byte, []int) {
	return file_special_admin_proto_rawDescGZIP(), []int{30}
}

func (x *OrderInfoForList) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderInfoForList) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *OrderInfoForList) GetCompletionDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletionDate
	}
	return nil
}

func (x *OrderInfoForList) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderInfoForList) GetOrderAmount() int64 {
	if x != nil {
		return x.OrderAmount
	}
	return 0
}

type GetOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*OrderInfoForList    `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersResponse) Reset() {
	*x = GetOrdersResponse{}
	mi := &file_special_admin_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersResponse) ProtoMessage() {}

func (x *GetOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_special_admin_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersResponse.ProtoReflect.Descriptor instead.
func (*GetOrdersResponse) Descriptor() ([]byte, []int) {
	return file_special_admin_proto_rawDescGZIP(), []int{31}
}

func (x *GetOrdersResponse) GetOrders() []*OrderInfoForList {
	if x != nil {
		return x.Orders
	}
	return nil
}

var File_special_admin_proto protoreflect.FileDescriptor

const file_special_admin_proto_rawDesc = "" +
	"\n" +
	"\x13special-admin.proto\x12\x0especial_app_v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1egoogle/protobuf/wrappers.proto\"J\n" +
	"\x11LittlePictureInfo\x12\x18\n" +
	"\apicture\x18\x01 \x01(\fR\apicture\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\"T\n" +
	"\vPictureInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\apicture\x18\x02 \x01(\fR\apicture\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\"p\n" +
	"\x14CreatePictureRequest\x12\x1b\n" +
	"\tparent_id\x18\x01 \x01(\tR\bparentId\x12;\n" +
	"\apicture\x18\x02 \x01(\v2!.special_app_v1.LittlePictureInfoR\apicture\"&\n" +
	"\x14DeletePictureRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x11\n" +
	"\x0fGetUsersRequest\"w\n" +
	"\bUserInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\asurname\x18\x02 \x01(\tR\asurname\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12!\n" +
	"\fphone_number\x18\x04 \x01(\tR\vphoneNumber\"B\n" +
	"\x10GetUsersResponse\x12.\n" +
	"\x05users\x18\x01 \x03(\v2\x18.special_app_v1.UserInfoR\x05users\"%\n" +
	"\x13GetIventInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x12\n" +
	"\x10GetIventsRequest\"\xe6\x02\n" +
	"\x12CreateIventRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x126\n" +
	"\bdatetime\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bdatetime\x121\n" +
	"\x05price\x18\x04 \x01(\v2\x1b.google.protobuf.Int64ValueR\x05price\x12\x1f\n" +
	"\vtotal_seats\x18\x05 \x01(\x03R\n" +
	"totalSeats\x12B\n" +
	"\x0eoccupied_seats\x18\x06 \x01(\v2\x1b.google.protobuf.Int64ValueR\roccupiedSeats\x12H\n" +
	"\x0elittle_picture\x18\a \x01(\v2!.special_app_v1.LittlePictureInfoR\rlittlePicture\"\xd9\x03\n" +
	"\x12UpdateIventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12;\n" +
	"\bdatetime\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\bdatetime\x88\x01\x01\x121\n" +
	"\x05price\x18\x05 \x01(\v2\x1b.google.protobuf.Int64ValueR\x05price\x12$\n" +
	"\vtotal_seats\x18\x06 \x01(\x03H\x03R\n" +
	"totalSeats\x88\x01\x01\x12B\n" +
	"\x0eoccupied_seats\x18\a \x01(\v2\x1b.google.protobuf.Int64ValueR\roccupiedSeats\x12M\n" +
	"\x0elittle_picture\x18\b \x01(\v2!.special_app_v1.LittlePictureInfoH\x04R\rlittlePicture\x88\x01\x01B\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_datetimeB\x0e\n" +
	"\f_total_seatsB\x11\n" +
	"\x0f_little_picture\"$\n" +
	"\x12DeleteIventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"n\n" +
	"\rUserIventInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\ruser_nickname\x18\x02 \x01(\tR\fuserNickname\x12(\n" +
	"\x10number_of_guests\x18\x03 \x01(\x03R\x0enumberOfGuests\"\xb6\x03\n" +
	"\x14GetIventInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x126\n" +
	"\bdatetime\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bdatetime\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x03R\x05price\x12\x1f\n" +
	"\vtotal_seats\x18\x06 \x01(\x03R\n" +
	"totalSeats\x12%\n" +
	"\x0eoccupied_seats\x18\a \x01(\x03R\roccupiedSeats\x12H\n" +
	"\x0elittle_picture\x18\b \x01(\v2!.special_app_v1.LittlePictureInfoR\rlittlePicture\x127\n" +
	"\bpictures\x18\t \x03(\v2\x1b.special_app_v1.PictureInfoR\bpictures\x12=\n" +
	"\n" +
	"userIvents\x18\n" +
	" \x03(\v2\x1d.special_app_v1.UserIventInfoR\n" +
	"userIvents\"\x98\x02\n" +
	"\x10IventInfoForList\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x126\n" +
	"\bdatetime\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bdatetime\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x12\x1f\n" +
	"\vtotal_seats\x18\x05 \x01(\x03R\n" +
	"totalSeats\x12%\n" +
	"\x0eoccupied_seats\x18\x06 \x01(\x03R\roccupiedSeats\x12H\n" +
	"\x0elittle_picture\x18\a \x01(\v2!.special_app_v1.LittlePictureInfoR\rlittlePicture\"M\n" +
	"\x11GetIventsResponse\x128\n" +
	"\x06ivents\x18\x01 \x03(\v2 .special_app_v1.IventInfoForListR\x06ivents\"$\n" +
	"\x12GetItemInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x11\n" +
	"\x0fGetItemsRequest\"\xab\x01\n" +
	"\x11CreateItemRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12H\n" +
	"\x0elittle_picture\x18\x04 \x01(\v2!.special_app_v1.LittlePictureInfoR\rlittlePicture\"\xf7\x01\n" +
	"\x11UpdateItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x12M\n" +
	"\x0elittle_picture\x18\x05 \x01(\v2!.special_app_v1.LittlePictureInfoH\x02R\rlittlePicture\x88\x01\x01B\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\x11\n" +
	"\x0f_little_picture\"#\n" +
	"\x11DeleteItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xf6\x01\n" +
	"\x13GetItemInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x12H\n" +
	"\x0elittle_picture\x18\x05 \x01(\v2!.special_app_v1.LittlePictureInfoR\rlittlePicture\x127\n" +
	"\bpictures\x18\x06 \x03(\v2\x1b.special_app_v1.PictureInfoR\bpictures\"\x97\x01\n" +
	"\x0fItemInfoForList\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12H\n" +
	"\x0elittle_picture\x18\x04 \x01(\v2!.special_app_v1.LittlePictureInfoR\rlittlePicture\"I\n" +
	"\x10GetItemsResponse\x125\n" +
	"\x05items\x18\x01 \x03(\v2\x1f.special_app_v1.ItemInfoForListR\x05items\"%\n" +
	"\x13GetOrderInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x12\n" +
	"\x10GetOrdersRequest\"w\n" +
	"\x12UpdateOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\x06status\x18\x02 \x01(\tH\x00R\x06status\x88\x01\x01\x12\x1d\n" +
	"\acomment\x18\x03 \x01(\tH\x01R\acomment\x88\x01\x01B\t\n" +
	"\a_statusB\n" +
	"\n" +
	"\b_comment\"$\n" +
	"\x12DeleteOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xd1\x01\n" +
	"\x14OrderItemInfoForList\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x03R\bquantity\x12H\n" +
	"\x0elittle_picture\x18\x06 \x01(\v2!.special_app_v1.LittlePictureInfoR\rlittlePicture\"\xf2\x02\n" +
	"\x14GetOrderInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06number\x18\x02 \x01(\tR\x06number\x12#\n" +
	"\ruser_nickname\x18\x03 \x01(\tR\fuserNickname\x127\n" +
	"\tform_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bformDate\x12C\n" +
	"\x0fcompletion_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0ecompletionDate\x12\x18\n" +
	"\acomment\x18\x06 \x01(\tR\acomment\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12!\n" +
	"\forder_amount\x18\b \x01(\x03R\vorderAmount\x12:\n" +
	"\x05items\x18\t \x03(\v2$.special_app_v1.OrderItemInfoForListR\x05items\"\xba\x01\n" +
	"\x10OrderInfoForList\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06number\x18\x02 \x01(\tR\x06number\x12C\n" +
	"\x0fcompletion_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0ecompletionDate\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12!\n" +
	"\forder_amount\x18\x05 \x01(\x03R\vorderAmount\"M\n" +
	"\x11GetOrdersResponse\x128\n" +
	"\x06orders\x18\x01 \x03(\v2 .special_app_v1.OrderInfoForListR\x06orders2\xc4\x10\n" +
	"\x13SpecialAdminService\x12`\n" +
	"\bGetUsers\x12\x1f.special_app_v1.GetUsersRequest\x1a .special_app_v1.GetUsersResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/users\x12r\n" +
	"\fGetIventInfo\x12#.special_app_v1.GetIventInfoRequest\x1a$.special_app_v1.GetIventInfoResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/ivents/{id}\x12d\n" +
	"\tGetIvents\x12 .special_app_v1.GetIventsRequest\x1a!.special_app_v1.GetIventsResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/ivents\x12n\n" +
	"\vCreateIvent\x12\".special_app_v1.CreateIventRequest\x1a$.special_app_v1.GetIventInfoResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/ivents\x12s\n" +
	"\vUpdateIvent\x12\".special_app_v1.UpdateIventRequest\x1a$.special_app_v1.GetIventInfoResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*2\x0f/v1/ivents/{id}\x12b\n" +
	"\vDeleteIvent\x12\".special_app_v1.DeleteIventRequest\x1a\x16.google.protobuf.Empty\"\x17\x82\xd3\xe4\x93\x02\x11*\x0f/v1/ivents/{id}\x12\x7f\n" +
	"\x12CreateIventPicture\x12$.special_app_v1.CreatePictureRequest\x1a$.special_app_v1.GetIventInfoResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/ivent_pictures\x12s\n" +
	"\x12DeleteIventPicture\x12$.special_app_v1.DeletePictureRequest\x1a\x16.google.protobuf.Empty\"\x1f\x82\xd3\xe4\x93\x02\x19*\x17/v1/ivent_pictures/{id}\x12n\n" +
	"\vGetItemInfo\x12\".special_app_v1.GetItemInfoRequest\x1a#.special_app_v1.GetItemInfoResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/items/{id}\x12`\n" +
	"\bGetItems\x12\x1f.special_app_v1.GetItemsRequest\x1a .special_app_v1.GetItemsResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/items\x12j\n" +
	"\n" +
	"CreateItem\x12!.special_app_v1.CreateItemRequest\x1a#.special_app_v1.GetItemInfoResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/items\x12o\n" +
	"\n" +
	"UpdateItem\x12!.special_app_v1.UpdateItemRequest\x1a#.special_app_v1.GetItemInfoResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*2\x0e/v1/items/{id}\x12_\n" +
	"\n" +
	"DeleteItem\x12!.special_app_v1.DeleteItemRequest\x1a\x16.google.protobuf.Empty\"\x16\x82\xd3\xe4\x93\x02\x10*\x0e/v1/items/{id}\x12|\n" +
	"\x11CreateItemPicture\x12$.special_app_v1.CreatePictureRequest\x1a#.special_app_v1.GetItemInfoResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/item_pictures\x12q\n" +
	"\x11DeleteItemPicture\x12$.special_app_v1.DeletePictureRequest\x1a\x16.google.protobuf.Empty\"\x1e\x82\xd3\xe4\x93\x02\x18*\x16/v1/item_pictures/{id}\x12r\n" +
	"\fGetOrderInfo\x12#.special_app_v1.GetOrderInfoRequest\x1a$.special_app_v1.GetOrderInfoResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/orders/{id}\x12d\n" +
	"\tGetOrders\x12 .special_app_v1.GetOrdersRequest\x1a!.special_app_v1.GetOrdersResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/orders\x12s\n" +
	"\vUpdateOrder\x12\".special_app_v1.UpdateOrderRequest\x1a$.special_app_v1.GetOrderInfoResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*2\x0f/v1/orders/{id}\x12b\n" +
	"\vDeleteOrder\x12\".special_app_v1.DeleteOrderRequest\x1a\x16.google.protobuf.Empty\"\x17\x82\xd3\xe4\x93\x02\x11*\x0f/v1/orders/{id}B-Z+special_admin/pkg/proto/v1;special_admin_v1b\x06proto3"

var (
	file_special_admin_proto_rawDescOnce sync.Once
	file_special_admin_proto_rawDescData []byte
)

func file_special_admin_proto_rawDescGZIP() []byte {
	file_special_admin_proto_rawDescOnce.Do(func() {
		file_special_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_special_admin_proto_rawDesc), len(file_special_admin_proto_rawDesc)))
	})
	return file_special_admin_proto_rawDescData
}

var file_special_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_special_admin_proto_goTypes = []any{
	(*LittlePictureInfo)(nil),     // 0: special_app_v1.LittlePictureInfo
	(*PictureInfo)(nil),           // 1: special_app_v1.PictureInfo
	(*CreatePictureRequest)(nil),  // 2: special_app_v1.CreatePictureRequest
	(*DeletePictureRequest)(nil),  // 3: special_app_v1.DeletePictureRequest
	(*GetUsersRequest)(nil),       // 4: special_app_v1.GetUsersRequest
	(*UserInfo)(nil),              // 5: special_app_v1.UserInfo
	(*GetUsersResponse)(nil),      // 6: special_app_v1.GetUsersResponse
	(*GetIventInfoRequest)(nil),   // 7: special_app_v1.GetIventInfoRequest
	(*GetIventsRequest)(nil),      // 8: special_app_v1.GetIventsRequest
	(*CreateIventRequest)(nil),    // 9: special_app_v1.CreateIventRequest
	(*UpdateIventRequest)(nil),    // 10: special_app_v1.UpdateIventRequest
	(*DeleteIventRequest)(nil),    // 11: special_app_v1.DeleteIventRequest
	(*UserIventInfo)(nil),         // 12: special_app_v1.UserIventInfo
	(*GetIventInfoResponse)(nil),  // 13: special_app_v1.GetIventInfoResponse
	(*IventInfoForList)(nil),      // 14: special_app_v1.IventInfoForList
	(*GetIventsResponse)(nil),     // 15: special_app_v1.GetIventsResponse
	(*GetItemInfoRequest)(nil),    // 16: special_app_v1.GetItemInfoRequest
	(*GetItemsRequest)(nil),       // 17: special_app_v1.GetItemsRequest
	(*CreateItemRequest)(nil),     // 18: special_app_v1.CreateItemRequest
	(*UpdateItemRequest)(nil),     // 19: special_app_v1.UpdateItemRequest
	(*DeleteItemRequest)(nil),     // 20: special_app_v1.DeleteItemRequest
	(*GetItemInfoResponse)(nil),   // 21: special_app_v1.GetItemInfoResponse
	(*ItemInfoForList)(nil),       // 22: special_app_v1.ItemInfoForList
	(*GetItemsResponse)(nil),      // 23: special_app_v1.GetItemsResponse
	(*GetOrderInfoRequest)(nil),   // 24: special_app_v1.GetOrderInfoRequest
	(*GetOrdersRequest)(nil),      // 25: special_app_v1.GetOrdersRequest
	(*UpdateOrderRequest)(nil),    // 26: special_app_v1.UpdateOrderRequest
	(*DeleteOrderRequest)(nil),    // 27: special_app_v1.DeleteOrderRequest
	(*OrderItemInfoForList)(nil),  // 28: special_app_v1.OrderItemInfoForList
	(*GetOrderInfoResponse)(nil),  // 29: special_app_v1.GetOrderInfoResponse
	(*OrderInfoForList)(nil),      // 30: special_app_v1.OrderInfoForList
	(*GetOrdersResponse)(nil),     // 31: special_app_v1.GetOrdersResponse
	(*timestamppb.Timestamp)(nil), // 32: google.protobuf.Timestamp
	(*wrapperspb.Int64Value)(nil), // 33: google.protobuf.Int64Value
	(*emptypb.Empty)(nil),         // 34: google.protobuf.Empty
}
var file_special_admin_proto_depIdxs = []int32{
	0,  // 0: special_app_v1.CreatePictureRequest.picture:type_name -> special_app_v1.LittlePictureInfo
	5,  // 1: special_app_v1.GetUsersResponse.users:type_name -> special_app_v1.UserInfo
	32, // 2: special_app_v1.CreateIventRequest.datetime:type_name -> google.protobuf.Timestamp
	33, // 3: special_app_v1.CreateIventRequest.price:type_name -> google.protobuf.Int64Value
	33, // 4: special_app_v1.CreateIventRequest.occupied_seats:type_name -> google.protobuf.Int64Value
	0,  // 5: special_app_v1.CreateIventRequest.little_picture:type_name -> special_app_v1.LittlePictureInfo
	32, // 6: special_app_v1.UpdateIventRequest.datetime:type_name -> google.protobuf.Timestamp
	33, // 7: special_app_v1.UpdateIventRequest.price:type_name -> google.protobuf.Int64Value
	33, // 8: special_app_v1.UpdateIventRequest.occupied_seats:type_name -> google.protobuf.Int64Value
	0,  // 9: special_app_v1.UpdateIventRequest.little_picture:type_name -> special_app_v1.LittlePictureInfo
	32, // 10: special_app_v1.GetIventInfoResponse.datetime:type_name -> google.protobuf.Timestamp
	0,  // 11: special_app_v1.GetIventInfoResponse.little_picture:type_name -> special_app_v1.LittlePictureInfo
	1,  // 12: special_app_v1.GetIventInfoResponse.pictures:type_name -> special_app_v1.PictureInfo
	12, // 13: special_app_v1.GetIventInfoResponse.userIvents:type_name -> special_app_v1.UserIventInfo
	32, // 14: special_app_v1.IventInfoForList.datetime:type_name -> google.protobuf.Timestamp
	0,  // 15: special_app_v1.IventInfoForList.little_picture:type_name -> special_app_v1.LittlePictureInfo
	14, // 16: special_app_v1.GetIventsResponse.ivents:type_name -> special_app_v1.IventInfoForList
	0,  // 17: special_app_v1.CreateItemRequest.little_picture:type_name -> special_app_v1.LittlePictureInfo
	0,  // 18: special_app_v1.UpdateItemRequest.little_picture:type_name -> special_app_v1.LittlePictureInfo
	0,  // 19: special_app_v1.GetItemInfoResponse.little_picture:type_name -> special_app_v1.LittlePictureInfo
	1,  // 20: special_app_v1.GetItemInfoResponse.pictures:type_name -> special_app_v1.PictureInfo
	0,  // 21: special_app_v1.ItemInfoForList.little_picture:type_name -> special_app_v1.LittlePictureInfo
	22, // 22: special_app_v1.GetItemsResponse.items:type_name -> special_app_v1.ItemInfoForList
	0,  // 23: special_app_v1.OrderItemInfoForList.little_picture:type_name -> special_app_v1.LittlePictureInfo
	32, // 24: special_app_v1.GetOrderInfoResponse.form_date:type_name -> google.protobuf.Timestamp
	32, // 25: special_app_v1.GetOrderInfoResponse.completion_date:type_name -> google.protobuf.Timestamp
	28, // 26: special_app_v1.GetOrderInfoResponse.items:type_name -> special_app_v1.OrderItemInfoForList
	32, // 27: special_app_v1.OrderInfoForList.completion_date:type_name -> google.protobuf.Timestamp
	30, // 28: special_app_v1.GetOrdersResponse.orders:type_name -> special_app_v1.OrderInfoForList
	4,  // 29: special_app_v1.SpecialAdminService.GetUsers:input_type -> special_app_v1.GetUsersRequest
	7,  // 30: special_app_v1.SpecialAdminService.GetIventInfo:input_type -> special_app_v1.GetIventInfoRequest
	8,  // 31: special_app_v1.SpecialAdminService.GetIvents:input_type -> special_app_v1.GetIventsRequest
	9,  // 32: special_app_v1.SpecialAdminService.CreateIvent:input_type -> special_app_v1.CreateIventRequest
	10, // 33: special_app_v1.SpecialAdminService.UpdateIvent:input_type -> special_app_v1.UpdateIventRequest
	11, // 34: special_app_v1.SpecialAdminService.DeleteIvent:input_type -> special_app_v1.DeleteIventRequest
	2,  // 35: special_app_v1.SpecialAdminService.CreateIventPicture:input_type -> special_app_v1.CreatePictureRequest
	3,  // 36: special_app_v1.SpecialAdminService.DeleteIventPicture:input_type -> special_app_v1.DeletePictureRequest
	16, // 37: special_app_v1.SpecialAdminService.GetItemInfo:input_type -> special_app_v1.GetItemInfoRequest
	17, // 38: special_app_v1.SpecialAdminService.GetItems:input_type -> special_app_v1.GetItemsRequest
	18, // 39: special_app_v1.SpecialAdminService.CreateItem:input_type -> special_app_v1.CreateItemRequest
	19, // 40: special_app_v1.SpecialAdminService.UpdateItem:input_type -> special_app_v1.UpdateItemRequest
	20, // 41: special_app_v1.SpecialAdminService.DeleteItem:input_type -> special_app_v1.DeleteItemRequest
	2,  // 42: special_app_v1.SpecialAdminService.CreateItemPicture:input_type -> special_app_v1.CreatePictureRequest
	3,  // 43: special_app_v1.SpecialAdminService.DeleteItemPicture:input_type -> special_app_v1.DeletePictureRequest
	24, // 44: special_app_v1.SpecialAdminService.GetOrderInfo:input_type -> special_app_v1.GetOrderInfoRequest
	25, // 45: special_app_v1.SpecialAdminService.GetOrders:input_type -> special_app_v1.GetOrdersRequest
	26, // 46: special_app_v1.SpecialAdminService.UpdateOrder:input_type -> special_app_v1.UpdateOrderRequest
	27, // 47: special_app_v1.SpecialAdminService.DeleteOrder:input_type -> special_app_v1.DeleteOrderRequest
	6,  // 48: special_app_v1.SpecialAdminService.GetUsers:output_type -> special_app_v1.GetUsersResponse
	13, // 49: special_app_v1.SpecialAdminService.GetIventInfo:output_type -> special_app_v1.GetIventInfoResponse
	15, // 50: special_app_v1.SpecialAdminService.GetIvents:output_type -> special_app_v1.GetIventsResponse
	13, // 51: special_app_v1.SpecialAdminService.CreateIvent:output_type -> special_app_v1.GetIventInfoResponse
	13, // 52: special_app_v1.SpecialAdminService.UpdateIvent:output_type -> special_app_v1.GetIventInfoResponse
	34, // 53: special_app_v1.SpecialAdminService.DeleteIvent:output_type -> google.protobuf.Empty
	13, // 54: special_app_v1.SpecialAdminService.CreateIventPicture:output_type -> special_app_v1.GetIventInfoResponse
	34, // 55: special_app_v1.SpecialAdminService.DeleteIventPicture:output_type -> google.protobuf.Empty
	21, // 56: special_app_v1.SpecialAdminService.GetItemInfo:output_type -> special_app_v1.GetItemInfoResponse
	23, // 57: special_app_v1.SpecialAdminService.GetItems:output_type -> special_app_v1.GetItemsResponse
	21, // 58: special_app_v1.SpecialAdminService.CreateItem:output_type -> special_app_v1.GetItemInfoResponse
	21, // 59: special_app_v1.SpecialAdminService.UpdateItem:output_type -> special_app_v1.GetItemInfoResponse
	34, // 60: special_app_v1.SpecialAdminService.DeleteItem:output_type -> google.protobuf.Empty
	21, // 61: special_app_v1.SpecialAdminService.CreateItemPicture:output_type -> special_app_v1.GetItemInfoResponse
	34, // 62: special_app_v1.SpecialAdminService.DeleteItemPicture:output_type -> google.protobuf.Empty
	29, // 63: special_app_v1.SpecialAdminService.GetOrderInfo:output_type -> special_app_v1.GetOrderInfoResponse
	31, // 64: special_app_v1.SpecialAdminService.GetOrders:output_type -> special_app_v1.GetOrdersResponse
	29, // 65: special_app_v1.SpecialAdminService.UpdateOrder:output_type -> special_app_v1.GetOrderInfoResponse
	34, // 66: special_app_v1.SpecialAdminService.DeleteOrder:output_type -> google.protobuf.Empty
	48, // [48:67] is the sub-list for method output_type
	29, // [29:48] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_special_admin_proto_init() }
func file_special_admin_proto_init() {
	if File_special_admin_proto != nil {
		return
	}
	file_special_admin_proto_msgTypes[10].OneofWrappers = []any{}
	file_special_admin_proto_msgTypes[19].OneofWrappers = []any{}
	file_special_admin_proto_msgTypes[26].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_special_admin_proto_rawDesc), len(file_special_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_special_admin_proto_goTypes,
		DependencyIndexes: file_special_admin_proto_depIdxs,
		MessageInfos:      file_special_admin_proto_msgTypes,
	}.Build()
	File_special_admin_proto = out.File
	file_special_admin_proto_goTypes = nil
	file_special_admin_proto_depIdxs = nil
}
